version: '3.1'

services:
  manim:
    # comment this line if you build the image to prevent overwriting the tag
    image: eulertour/manim:latest
    # uncomment this line to build rather than pull the image
    #build: .
    entrypoint:
      - manim
      - --media_dir=/tmp/output
    volumes:
      - .:/tmp/input
      - .:/tmp/output
    working_dir: /tmp/input
    network_mode: "none"
    #command: "/bin/bash"
    #command: "SimpleText.py Coordinates" 
